name: 132.00stable (1) AlmaLinux 8 + Nginx Modsecurity Enabled

on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.release || github.event.client_payload.release }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Sysbox
      run: |
        curl -LO https://downloads.nestybox.com/sysbox/releases/v0.6.7/sysbox-ce_0.6.7-0.linux_amd64.deb
        sudo dpkg -i sysbox-ce_0.6.7-0.linux_amd64.deb || sudo apt-get install -f

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build 
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfiles/Dockerfile-almalinux8
        platforms: linux/amd64
        load: true
        tags: cmm_el89:latest

    - name: Debug payload (repository_dispatch)
      run: echo ${{ github.event.client_payload.release }}
      
    - name: Debug input (workflow_dispatch)
      run: echo ${{ github.event.inputs.release }}

    - name: Run container Centmmin Mod LEMP AlmaLinux 8 Install
      run: |
        docker run -d --name=cmm_el89 --runtime=sysbox-runc --cap-add=SYS_ADMIN --security-opt seccomp=unconfined --security-opt label=disable --security-opt apparmor=unconfined -v /tmp/$(mktemp -d):/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro cmm_el89:latest
        sleep 4
        docker exec cmm_el89 bash -c "mkdir -p /etc/centminmod"
        docker exec cmm_el89 bash -c "echo 'NGINX_MODSECURITY=y' >> /etc/centminmod/custom_config.inc"
        docker exec cmm_el89 bash -c "curl -4sL https://centminmod.com/installer.sh | bash" | tee cmm-install.log
        output=$(tail -20 cmm-install.log)
        echo "$output" >> $GITHUB_STEP_SUMMARY
      continue-on-error: true

    - name: Display Centmmin Mod LEMP Install Log
      run: |
        echo "Last 20 lines of Centmmin Mod LEMP Install Log:"
        echo "----------------------------------------"
        tail -20 cmm-install.log
        echo "----------------------------------------"
      continue-on-error: true

    - name: Inspect nginx uid/gid
      run: |
        docker exec cmm_el89 bash -c "id nginx; echo"
        docker exec cmm_el89 bash -c "ls -lahn /home/nginx"
      continue-on-error: true

    - name: Check pure-ftpd virtual FTP user login
      run: |
        # Add pure-ftpd virtual user
        docker exec cmm_el89 bash -c 'openssl dhparam -out /etc/ssl/private/pure-ftpd-dhparams.pem 2048 >/dev/null 2>&1 && systemctl restart pure-ftpd'
        docker exec cmm_el89 bash -c '( echo "ftppass" ; echo "ftppass" ) | pure-pw useradd ftpuser -u nginx -g $(id -g nginx) -d "/home/nginx/domains/demodomain.com"; pure-pw mkdb'
        # Get container IP address
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cmm_el89)         
        # Install lftp
        docker exec cmm_el89 bash -c 'yum -q -y install lftp'
        # Test FTP login using lftp
        docker exec cmm_el89 bash -c "lftp -e 'set ftp:passive-mode yes; set ftp:ssl-allow yes; set ftp:ssl-force yes; set ssl:verify-certificate no; open -u ftpuser,ftppass -p 21 ftp://$CONTAINER_IP; ls'"
      continue-on-error: true

    - name: Nginx Configure
      run: |
        docker exec cmm_el89 bash -c "cat /root/centminlogs/nginx-configure-*"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: Nginx Patches
      run: |
        docker exec cmm_el89 bash -c "cat /root/centminlogs/patch_patchnginx_*"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: PHP-FPM Patches
      run: |
        docker exec cmm_el89 bash -c "cat /root/centminlogs/patch_php_*"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: Disk Usage Analysis
      run: |
        docker exec cmm_el89 bash -c "du -sh /svr-setup"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "df -hT"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "rpm -qa --queryformat '%10{size} - %-25{name} \t %{version}\n' | sort -n"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: centmin.sh setup
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "echo '1' > /etc/centminmod/email-primary.ini"
        docker exec cmm_el89 bash -c "echo '2' > /etc/centminmod/email-secondary.ini"
      continue-on-error: true

    - name: YUM repolist all
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "yum repolist all"
      continue-on-error: true

    - name: Inspect wget install
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "/usr/local/bin/wget -V"
        docker exec cmm_el89 bash -c "/usr/bin/wget -V"
      continue-on-error: true

    - name: Inspect ccache install
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "/usr/local/bin/ccache -V"
        sleep 1
        docker exec cmm_el89 bash -c "/usr/local/bin/ccache -s"
        sleep 1
        docker exec cmm_el89 bash -c "grep ccache ~/.bashrc"
      continue-on-error: true

    - name: Inspect ccache YUM install
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "/usr/bin/ccache -V"
        sleep 1
        docker exec cmm_el89 bash -c "/usr/bin/ccache -s"
        sleep 1
        docker exec cmm_el89 bash -c "grep ccache ~/.bashrc"
      continue-on-error: true

    - name: Inspect PHP-FPM setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "systemctl restart php-fpm.service"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "journalctl -xe --no-pager | tail -n 35"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "systemctl status php-fpm.service"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "php-config || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "/usr/local/bin/php --ini"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ldd /usr/local/bin/php"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "/usr/local/bin/php -v"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAhrt \$(php-config --extension-dir || true)"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: Inspect Nginx setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /usr/local/nginx/logs || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /usr/local/nginx/modules || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /usr/local/nginx/conf/lua-package-path-include.conf || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /usr/local/nginx-dep/lib/lua/5.1/resty/ || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /usr/local/nginx-dep/lib/lua/5.1/resty/core || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /usr/local/nginx/conf/lua-package-path-include.conf || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "grep 'lua-package-path-include.conf' /usr/local/nginx/conf/nginx.conf || true"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /usr/local/nginx/logs/nginx.pid || true"
        sleep 1
        docker exec cmm_el89 bash -c "ps aux | grep nginx"
        sleep 1
        docker exec cmm_el89 bash -c "systemctl status nginx.service"
        sleep 1
        docker exec cmm_el89 bash -c "curl -I http://localhost" || true
        docker exec cmm_el89 bash -c "echo '---'" || true
        docker exec cmm_el89 bash -c "curl -sIv http://localhost" || true
        docker exec cmm_el89 bash -c "echo '---'" || true
        docker exec cmm_el89 bash -c "/usr/local/sbin/nginx -V" || true
        docker exec cmm_el89 bash -c "echo '---'" || true
        docker exec cmm_el89 bash -c "ldd /usr/local/sbin/nginx" || true
        docker exec cmm_el89 bash -c "echo '---'" || true
        docker exec cmm_el89 bash -c "nginx -t" || true
        docker exec cmm_el89 bash -c "echo '---'" || true
      continue-on-error: true

    - name: Inspect MariaDB setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "systemctl status mariadb.service"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /etc/my.cnf"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c 'mysql -t -e "SELECT * FROM mysql.plugin;"'
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c 'mysql -t -e "SHOW PLUGINS;"'
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "mysqladmin var | tr -s ' '"
      continue-on-error: true

    - name: Inspect Python3 setup
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "python3 --version"
        sleep 1
        docker exec cmm_el89 bash -c "pip --version"
        sleep 1
        docker exec cmm_el89 bash -c "alternatives --list | grep -E -i 'pip|python' || echo 'No match for pip or python keywords'"
      continue-on-error: true

    - name: Inspect Redis Server setup
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "redis-cli info"
        sleep 1
        docker exec cmm_el89 bash -c "systemctl status redis"
        sleep 1
        docker exec cmm_el89 bash -c "php --ri redis"
      continue-on-error: true

    - name: Inspect pure-ftpd setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /etc/systemd/system/pure-ftpd.service.d"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /etc/systemd/system/pure-ftpd.service.d/pidfile.conf"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "journalctl -u pure-ftpd --no-pager | tail -n 100"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "systemctl status pure-ftpd.service"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "ls -lAh /etc/ssl/private/pure-ftpd-dhparams.pem || echo '/etc/ssl/private/pure-ftpd-dhparams.pem not yet setup'"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /etc/pure-ftpd/pure-ftpd.conf | grep -E 'UnixAuthentication|VerboseLog|PureDB |CreateHomeDir|TLS|PassivePortRange|TLSCipherSuite|MaxClientsNumber|MaxClientsPerIP|NoAnonymous|Umask'"
      continue-on-error: true

    - name: Inspect chronyd setup
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "journalctl -u chronyd --no-pager | tail -n 100"
        sleep 1
        docker exec cmm_el89 bash -c "systemctl status chronyd.service || echo 'chronyd not supported in docker containers'"
      continue-on-error: true

    - name: Inspect CSF Firewall setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "grep -E '^TCP_IN|^TCP6_IN' /etc/csf/csf.conf"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "csf -v"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "csf -ra"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "cat /etc/csf/csf.allow"
      continue-on-error: true

    - name: Inspect logrotation setup
      run: |
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "logrotate -dv /etc/logrotate.d/nginx"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "logrotate -dv /etc/logrotate.d/php-fpm"
      continue-on-error: true

    - name: Inspect Sysstat and systemd-journald service
      run: |
        docker exec cmm_el89 bash -c "systemctl status sysstat.service"
        docker exec cmm_el89 bash -c "systemctl status systemd-journald.service"
      continue-on-error: true
    
    - name: Check permissions of /var/log/journal
      run: |
        docker exec cmm_el89 bash -c "ls -ld /var/log/journal || echo '/var/log/journal persistent storage not configured'"
      continue-on-error: true
    
    - name: Show recent systemd-journald logs
      run: |
        docker exec cmm_el89 bash -c "journalctl --unit=systemd-journald.service --no-pager | tail -n 100"
      continue-on-error: true

    - name: Run cminfo
      run: |
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/tools/cminfo.sh"
      continue-on-error: true

    - name: Run addons/golang.sh
      run: |
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/addons/golang.sh install"
      continue-on-error: true

    - name: Run addons/nodejs.sh
      run: |
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/addons/nodejs.sh install"
      continue-on-error: true

    - name: Run addons/opendkim.sh
      run: |
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/addons/opendkim.sh"
      continue-on-error: true

    - name: Run tools/csfcf.sh
      run: |
        sleep 1
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/tools/csfcf.sh"
        sleep 1
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/tools/csfcf.sh auto"
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/tools/csfcf.sh ipv4"
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/tools/csfcf.sh ipv6"
      continue-on-error: true

    - name: Create Nginx HTTPS vhost
      run: |
        docker exec cmm_el89 bash -c "/usr/bin/nv -d domain.com -s y"
      continue-on-error: true

    - name: Test mysqladmin_shell.sh MySQL Database Management
      run: |
        docker exec cmm_el89 bash -c "echo -e 'dbname dbusername dbpassword\ndb2name db2username db2password' > /home/nginx/domains/domain.com/dbfile.txt"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "echo 'multidb'"
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/addons/mysqladmin_shell.sh multidb /home/nginx/domains/domain.com/dbfile.txt"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "echo 'createuserdb'"
        docker exec cmm_el89 bash -c "/usr/local/src/centminmod/addons/mysqladmin_shell.sh createuserdb mydbname mydbuser mydbpass"
        docker exec cmm_el89 bash -c "echo '---'"
        docker exec cmm_el89 bash -c "echo 'showgrants'"
        docker exec cmm_el89 bash -c "echo 'dbusername' | /usr/local/src/centminmod/addons/mysqladmin_shell.sh showgrants"
        docker exec cmm_el89 bash -c "echo 'db2username' | /usr/local/src/centminmod/addons/mysqladmin_shell.sh showgrants"
        docker exec cmm_el89 bash -c "echo 'mydbuser' | /usr/local/src/centminmod/addons/mysqladmin_shell.sh showgrants"
        docker exec cmm_el89 bash -c "echo '---'"
      continue-on-error: true

    - name: Run cmupdate
      run: |
        docker exec cmm_el89 bash -c "cmupdate"
      continue-on-error: true

    - name: centmin.sh menu option 4 Nginx upgrade test
      run: |
        docker exec cmm_el89 /home/centmin-option-4.sh
        docker exec cmm_el89 bash -c "ccache -s"
      continue-on-error: true

    - name: YUM History Info
      run: |
        docker exec cmm_el89 bash -c "for id in \$(/usr/bin/yum history list | awk '{print \$1}' | grep -E '^[0-9]+$'); do /usr/bin/yum history info \$id; done"
      continue-on-error: true

    - name: Copy AlmaLinux Centmin Mod logs from container
      # don‚Äôt fail the job if this step errors
      continue-on-error: true
      run: |
        mkdir -p ./centminlogs
        # check container is still running (or at least exists)
        CONTAINER_EXISTS=$(docker ps -aq -f name=cmm_el89)
        if [ -z "$CONTAINER_EXISTS" ]; then
          echo "‚ùå Container cmm_el89 not found; skipping log copy"
          exit 0
        fi

        # check for the logs directory inside the container
        if docker exec cmm_el89 test -d /root/centminlogs; then
          echo "üìÇ Found /root/centminlogs ‚Äì copying out‚Ä¶"
          docker exec cmm_el89 tar -C /root/centminlogs -cf - . | tar -C ./centminlogs -xf -
        else
          echo "‚ö†Ô∏è /root/centminlogs not present in container; skipping log copy"
        fi

    - name: Upload AlmaLinux Centmin Mod Logs
      uses: actions/upload-artifact@v4
      with:
        name: almalinux_logs
        path: centminlogs/*

    - name: Trigger Edge Workflow
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.PAT }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/almalinux8-edge-13100stable.yml/dispatches \
        -d '{"ref":"master"}'

  discordNotificationSuccess:
    needs: build
    if: ${{ success() }} # Only run this job if the previous job was successful
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord Success
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\":\"Workflow '${{ github.workflow }}' was triggered by '${{ github.event_name }}' and completed successfully!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

  discordNotificationFailure:
    needs: build
    if: ${{ failure() }} # Only run this job if the previous job was unsuccessful
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord Failure
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\":\"Workflow '${{ github.workflow }}' was triggered by '${{ github.event_name }}' and failed!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}